version: '3.5'

x-env: &env
  PUID: "99"
  PGID: "100"
  TZ: "Europe/London"

services:
  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      PUID: "99"
      PGID: "100"
      TZ: "Europe/London"
    ports:
      - 6767:6767
    volumes:
      - "bazarr:/config"
      - "/mnt/user/video/films:/movies"
      - "/mnt/user/video/tv:/tv"
      - "/mnt/user/video/documentaries:/documentaries"
      - "/mnt/user/appdata/downloads/complete:/downloads"
      - /etc/localtime:/etc/localtime:ro

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      PUID: "99"
      PGID: "100"
      TZ: "Europe/London"
    ports:
      - 7878:7878
    volumes:
      - radarr:/config
      - "/mnt/user/video/films:/movies"
      - "/mnt/user/video/documentaries:/documentaries"
      - "/mnt/user/appdata/downloads/complete:/downloads"
      - /etc/localtime:/etc/localtime:ro

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      PUID: "99"
      PGID: "100"
      TZ: "Europe/London"
    ports:
      - 8989:8989
    volumes:
      - sonarr:/config
      - "/mnt/user/video/tv:/tv"
      - "/mnt/user/video/documentaries:/documentaries"
      - "/mnt/user/appdata/downloads/complete:/downloads"
      - /etc/localtime:/etc/localtime:ro

volumes:
  sonarr:
  radarr:
  bazarr: